ALTER TABLE DEPOSIT 
ADD CITY VARCHAR(20),PINCODE INT

ALTER TABLE DEPOSIT 
ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT

EXEC SP_RENAME 'DEPOSIT.ACTNO', 'ANO'

ALTER TABLE DEPOSIT
DROP COLUMN CITY

EXEC SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'

----------PART B ----------

EXEC SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE

EXEC SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME'

-------PART C---------

CREATE TABLE STUDENT_DETAILS(
	Enrollment_No VARCHAR(20),
	Name VARCHAR(25),
	CPI DECIMAL(5,2),
	Birthdate DATETIME
);

ALTER TABLE STUDENT_DETAILS
ADD CITY VARCHAR(20),Backlog INT 

SELECT * FROM STUDENT_DETAILS

ALTER TABLE STUDENT_DETAILS
ALTER COLUMN NAME VARCHAR(35)

ALTER TABLE STUDENT_DETAILS
ALTER COLUMN CPI INT

EXEC SP_RENAME 'STUDENT_DETAILS.Enrollment_No' , 'ENO'

ALTER TABLE STUDENT_DETAILS
DROP COLUMN CITY

EXEC SP_RENAME 'STUDENT_DETAILS' , 'STUDENT_MASTER'

-----DELETE, Truncate, Drop Operation------

----------------Part – A: -----------------











